### ISSUE TITLE
Ordering aliases in suggestions

### ISSUE THREAD

**Issue by disco-volante** [coderGtm/yantra-app-launcher#221] opened 2024-09-24 14:50 UTC
It would be great to be able to order aliases that are being displayed in suggestions either by hand or with params like last used or frequency.
The best option would be to expose them to current suggestion ordering view in settings so that the order of all suggestions can be changed according to one's preferences.

**Comment by coderGtm** [comment] 2024-09-24 14:52
In the latest update (v9.8.0) you can manually reorder the primary suggestions from setting according to your preference.

**Comment by disco-volante** [comment] 2024-09-24 16:20
But as far as I can see (I have 9.8.0 from play store) this does not include the user aliases that seem to be attached to the suggestions list but I don't see them in the settings. Only the default aliases for PWD etc.

**Comment by Anready** [comment] 2024-09-24 16:25
> But as far as I can see (I have 9.8.0 from play store) this does not include the user aliases that seem to be attached to the suggestions list but I don't see them in the settings. Only the default aliases for PWD etc.

no, alias also in it, i also think so, but no, alias included, check carefully

**Comment by disco-volante** [comment] 2024-09-24 16:51
Maybe I'm missing something but this is what I have on main screen suggestions, all but two default are hidden, and user defined are displayed from the third position:
![Screenshot_20240924-184726](https://github.com/user-attachments/assets/685f344a-d6a3-4a16-a103-0f6a00b02cf5)

...and in settings the list ends on predefined aliases
![Screenshot_20240924-184525](https://github.com/user-attachments/assets/452f9982-0c09-4263-a307-107911035118)

I've reset the launcher prior to that.

**Comment by coderGtm** [comment] 2024-09-30 07:07
I still can't reproduce this. I've checked and those appear in my list too. Please once again check the whole list. It's easy to miss out when scrolling through such a long list.

**Comment by disco-volante** [comment] 2024-10-03 07:45
It did work but only after resetting the suggestions list which removed all the previous customizations. Unfortunately restoring the backup did not work on the new list so all the hidden items need to be restored manually.

**Comment by coderGtm** [comment] 2024-10-03 08:04
Which customizations? The suggestion reordering?

**Comment by coderGtm** [comment] 2024-10-03 08:06
Ok I can see it now. There is certainly a bug here!

**Comment by coderGtm** [comment] 2024-10-03 08:13
Tracking this bug here #230

**Comment by coderGtm** [comment] 2024-10-17 14:24
Fixed by #235

**Closed by coderGtm** 2024-10-17 14:24 UTC
Labels: feature-request
